# Generated by Django 2.0.13 on 2019-06-19 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
