# Generated by Django 2.0.13 on 2019-06-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='setor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setores.Setores'),
        ),
    ]
