# Generated by Django 2.0.13 on 2019-06-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='setor',
        ),
    ]
