# Generated by Django 2.0.13 on 2019-06-20 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('prioridade', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, default='Não Realizado', max_length=20)),
                ('usuario', models.CharField(blank=True, default='sem usuario', max_length=50)),
                ('anexo', models.FileField(blank=True, default=None, upload_to='files/')),
                ('solucao', models.CharField(blank=True, default='', max_length=250)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
