# Generated by Django 2.0.13 on 2019-06-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaChamado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='setor',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
