# Generated by Django 2.0.13 on 2019-05-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaChamado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='prioridade',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
