# Generated by Django 2.0.13 on 2019-06-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaChamado', '0002_chamados_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='para_usuario',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
