# Generated by Django 2.0.13 on 2019-05-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaChamado', '0002_chamados_prioridade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamados',
            name='data_criacao',
        ),
        migrations.AlterField(
            model_name='chamados',
            name='prioridade',
            field=models.CharField(max_length=150),
        ),
    ]
