# Generated by Django 2.0.13 on 2019-05-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaChamado', '0004_auto_20190516_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamados',
            old_name='titulo',
            new_name='assunto',
        ),
    ]
