# Generated by Django 2.0.13 on 2019-05-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaChamado', '0006_auto_20190516_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='admin',
            field=models.CharField(blank=True, default='off', max_length=10),
        ),
    ]
