# Generated by Django 2.0.13 on 2019-05-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaChamado', '0007_auto_20190517_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='solucao',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='status',
            field=models.CharField(blank=True, default='Não Realizado', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='usuario',
            field=models.CharField(blank=True, default='admin', max_length=50),
        ),
    ]
