# Generated by Django 2.0.13 on 2019-05-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaChamado', '0008_auto_20190517_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='solucao',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
