# Generated by Django 2.0.13 on 2019-05-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaChamado', '0010_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
